# Site settings
title: 小雾博
SEOTitle: 小雾博的主网站 | 小雾博
header-img: img/home-bg.jpg
email: 2010965900@qq.com
description: "这里是 小雾博 的个人主网站，与你一起发现更大的世界"
keyword: "小雾博, 永无止境的爱, 心烦意乱, 阿白, 和平精英, @小雾博, 小雾博的主网站, XiaoWubo, 坤鹏, 个人网站, 互联网, Web, JavaScript, 原神, 我的世界, 前端, 设计"
url: "https://xiaowubo418.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: XiaoWubo
zhihu_username: XiaoWubo
github_username: XiaoWubo
twitter_username: XiaoWubo
#facebook_username:  XiaoWubo
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "成为一个root大牛"
sidebar-avatar: xiaowubo.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
